### ISSUE TITLE
Synchronization with chain

### ISSUE THREAD

**Issue by AndreiAndrusyshyn** [NewEconoLab/neo-cli-nel#2]
**I'm submitting a bug report**

When started neo-cli-nel there is no synchronization with chain.
![image](https://user-images.githubusercontent.com/28659649/71441620-e72f1480-270a-11ea-8fc9-5ca3d1bcb21d.png)
![image](https://user-images.githubusercontent.com/28659649/71441634-f746f400-270a-11ea-9516-eb8caafb792b.png)
![image](https://user-images.githubusercontent.com/28659649/71441644-029a1f80-270b-11ea-8c21-df0f5e8df95a.png)

There is no blocks sync, no block height.

And sometimes seed just droped
![image](https://user-images.githubusercontent.com/28659649/71441591-c961af80-270a-11ea-9a0e-22f6c72df53a.png)

* Expected sync of blocks in cli to use node. 
Expected that should be some fix of it, because of this it is impossible to use this cli.

* **Steps to reproduce:**
1. Clone repo from git
2. Branch should be master
3. Build it used dotnet / visual studio
4. Run cli
5. Get state

* **Environment on first machine:** 
     - OS Name:                   Microsoft Windows 10 Pro
     - OS Version:                10.0.18363 N/A Build 18363
     - System Type:               x64-based PC
     - Processor(s):              1 Processor(s) Installed.   Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~2401 Mhz

* **Environment on second machine:** 
Env is same except OS is Ubuntu 19.04

* **Other information** 
Trying to build in two different modes Release Debug and changing package neodebug version.

**Comment by ghost** [comment]
So I solved this problem with proper configuration
First of all, it should be noted that port of seed given in explorer :

![image](https://user-images.githubusercontent.com/59236907/71477043-985baa80-27f0-11ea-961f-8c1038c36440.png)

is different with port which should be specified in config. In this case give port in explorer is 20332 but to config should be written 20333.

Second one is , that should be MaxGasInvoke specified. 

![image](https://user-images.githubusercontent.com/59236907/71477144-1324c580-27f1-11ea-8a9c-5af360ca96ae.png)


Third one ( optional ), ip binding address should be specified obviously

![image](https://user-images.githubusercontent.com/59236907/71477166-318ac100-27f1-11ea-9df7-ff50bb3e1869.png)

And port should be changed , due to the coincidence of the connection port seed ( with give port seeds is disconnected ), below is working example: 

![image](https://user-images.githubusercontent.com/59236907/71477315-f8068580-27f1-11ea-9ea9-cf012becccd3.png)



And the last but not least , there is mistake in system fee in protocol copnfig. With given parameters, synchronization speed is extremely low or even not possible.
Below is the working setting:
![image](https://user-images.githubusercontent.com/59236907/71477223-84647880-27f1-11ea-9fe5-694d441ad147.png)
